### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by zdefne-usgs** [esturdivant-usgs/science-base-automation#23]
When I run the the latest version I get the following error:
```
  File "C:/Users/zdefne/Documents/PYTHON/science-base-automation/config_autoSB.py", line 20, in <module>
    from autoSB import *

AttributeError: 'module' object has no attribute 'add_element_to_xmlmap_newvals2xml'
```

**Comment by esturdivant-usgs** [comment]
I think you must have downloaded a version at exactly the wrong time. I also made a mistake in pushing a change with something incomplete. 

A hack fix to this without updating to the current version is to delete the `__all__ = [...]` from autoSB.py.

The source of the problem is probably that I was missing a comma in that list.

**Comment by zdefne-usgs** [comment]
I see the missing comma in the list. Fixing it fixed the issue...
